package com.github.henkexbg.gallery.config;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.Resource;
import org.jdbi.v3.core.Jdbi;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Configuration;

@Configuration
public class DbTableSetup {

    private final Logger LOG = LoggerFactory.getLogger(getClass());

    @Resource
    Jdbi jdbi;

    @PostConstruct
    public void executeCreateTable() {
        try {
            jdbi.useHandle(handle -> {
                handle.execute("""
                        CREATE TABLE IF NOT EXISTS location (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            the_geom GEOMETRY,
                            name VARCHAR(255),
                            country_iso_a2 VARCHAR(5),
                            feature_code VARCHAR(10)
                        );
                        """);
                handle.execute("CREATE SPATIAL INDEX IF NOT EXISTS geom_index ON location (the_geom)");

                handle.execute("""
                        CREATE TABLE IF NOT EXISTS gallery_file (
                            id IDENTITY PRIMARY KEY,
                            parent_id BIGINT,
                            path_on_disk VARCHAR(2048) UNIQUE NOT NULL,
                            is_directory BOOLEAN NOT NULL,
                            file_type ENUM('IMAGE', 'VIDEO'),
                            content_type VARCHAR(100),
                            location GEOMETRY,
                            date_taken TIMESTAMP,
                            last_modified TIMESTAMP NOT NULL,
                            FOREIGN KEY (parent_id) REFERENCES gallery_file(id) ON DELETE CASCADE
                        )
                        """);
                handle.execute("CREATE INDEX IF NOT EXISTS path_index ON gallery_file (path_on_disk)");
                handle.execute("CREATE INDEX IF NOT EXISTS date_taken_index ON gallery_file (date_taken)");
                handle.execute("CREATE INDEX IF NOT EXISTS last_modified_index ON gallery_file (last_modified)");

                handle.execute("""
                        CREATE TABLE IF NOT EXISTS tag (
                            id IDENTITY PRIMARY KEY,
                            file_id BIGINT,
                            text VARCHAR_IGNORECASE(255) NOT NULL,
                            type VARCHAR_IGNORECASE(20),
                            source ENUM('FILENAME', 'LOCATION'),
                            FOREIGN KEY (file_id) REFERENCES gallery_file(id) ON DELETE CASCADE
                        )
                        """);
                handle.execute("CREATE INDEX IF NOT EXISTS tag_index ON tag (text)");
                handle.execute("CREATE INDEX IF NOT EXISTS tag_type_index ON tag (type)");
            });
        } catch (Exception e) {
            LOG.error("Error when setting up database tables!", e);
            throw e;
        }
    }

}
